config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'movies', to: 'movies#index'
  get 'movies/new'
  get 'movies/list', to:'movies#list'
  post 'movies', to: 'movies#create'
  get 'movies/:id', to:'movies#show', as:'movie'
  get 'movies/:id/edit', to:'movies#edit', as:'movie_edit'
  patch 'movies/:id', to:'movies#update'
  delete 'movies/:id', to:'movies#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

    before_action :find_movie, only: [:show, :edit, :update, :destroy]

    def index
        @movies = Movie.all
    end

    def new
        @movie = Movie.new
    end

    def create
        @movie = Movie.new(movie_params)
        @movie.favorite = false
        @movie.save
        redirect_to movies_path
    end

    def show
        
    end

    def edit
        
    end

    def update
        @movie.update(movie_params)
        redirect_to movies_path
    end

    def destroy
        @movie.delete
        redirect_to movies_path
    end
 

    def list
        @movies = Movie.all
    end

    private

    def movie_params
        params.require(:movie).permit(:name, :year, :favorite)
    end

    def find_movie
        @movie = Movie.find(params[:id])
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VideoStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <div class="container">
    <%= yield %>
  </div>
    

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> 
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: @movie, local: true) do |f| %>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>
    <%= f.label :year, "Year" %>
    <%= f.text_field :year %>
    <%= f.label :favorite, "favorite" %>
    <%= f.check_box :favorite  %>
    <%= f.submit "enviar" %>
<% end %>

app/views/movies/edit.html.erb
<h1>formulario de edit de pelicula</h1>

<%= render 'movies/form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1>index</h1>

<div class="row">
    <% @movies.each do |movie| %>
        <div class="col-lg-3">
        <%= movie.name %>
        <%= movie.year %>
        <%= movie.favorite %>
        <%= link_to 'show', movie_path(movie) %>
        
        <%= link_to 'edit',  movie_edit_path(movie) %> 
        <%= link_to 'delete', movie, method: :delete %>
        <i class="fa fa-check" aria-hidden="true"></i>

        </div>
        

    <% end %>

</div>
<br>


<div class="d-flex  ">
    <div class="border border-primary">
        <a href="movies/list"><i class="fa fa-github" aria-hidden="true"></i>
</a>

    </div>
    <div class="border border-primary">
        <a href="movies/new"><i class="fa fa-rebel" aria-hidden="true"></i></a>
    </div>
        
        
</div>

app/views/movies/list.html.erb
<h1>listar</h1>

<div class="row">
    <div class="col-lg-4">
        <h4>FAVORITO</h4>
        <% @movies.each do |movie| %>
            <%if movie.favorite %>
            <div class="col-lg-auto">
                
                <%= movie.name %>
                <%= movie.year %>
                <%= movie.favorite %>
            </div>
    
            <% end %>
    
        <% end %>
    </div>

    <div class="col-lg-4">
        <h4>NO FAVORITO</h4>
        <% @movies.each do |movie| %>
        <%if !movie.favorite %>
        <div class="col-lg-auto">
            
            <%= movie.name %>
            <%= movie.year %>
            <%= movie.favorite %>
        </div>
    
        <% end %>
    
        <% end %>
    </div>


</div>





<%= link_to 'back', movies_path %>

app/views/movies/new.html.erb
<h1>formulario de ingreso de pelicula</h1>

<%= render 'movies/form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<h1>Pelicula</h1>

<%= @movie.name %>
<%= @movie.year %>
<%= @movie.favorite %>

<%=link_to 'back', movies_path%>